# Generated by Django 6.1 on 2026-08-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_student_name_alter_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Pre-Intermediate', 'Pre-Intermediate'), ('Intermediate', 'Intermediate')], max_length=30)),
                ('lesson_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='lessons/videos/')),
            ],
            options={
                'ordering': ['level', 'lesson_number'],
                'unique_together': {('level', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='LessonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lessons/images/')),
                ('image_order', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portal.lesson')),
            ],
            options={
                'ordering': ['image_order'],
            },
        ),
        migrations.CreateModel(
            name='StudentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='portal.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_lessons', to='portal.student')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
