# Generated by Django 6.1 on 2026-09-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_lesson_video_lesson_pdf_videolesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='Shiza123@', max_length=100),
            preserve_default=False,
        ),
    ]
