# Generated by Django 6.1 on 2026-09-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_student_phone_remove_student_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='student1', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
