# Generated by Django 6.1 on 2026-09-13 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_student_email_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of admission (sets monthly billing cycle date)'),
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Standard monthly fee for this student', max_digits=10),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Pre-Intermediate', 'Pre-Intermediate'), ('Intermediate', 'Intermediate'), ('Course Completion', 'Course Completion')], max_length=50)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='portal.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('billing_month', models.CharField(help_text='e.g. September 2026', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Unpaid', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_vouchers', to='portal.student')),
            ],
        ),
    ]
