# Generated by Django 6.1 on 2026-09-14 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_student_admission_date_student_monthly_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_due_day',
            field=models.PositiveSmallIntegerField(default=5, help_text='Day of the month the voucher is generated and due (1 to 28)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of admission'),
        ),
    ]
